prefix = "pcarey"
username = "pcarey" // replace with var.owner from root dir?
email = "pcarey@hashicorp.com"
aws_key_name = "pcarey-mac"
ssh_key = "/Users/patrick/.ssh/id_rsa"
hcp_vault_cluster_id = "vault-cluster-au"
hcp_vault_hvn = "pcarey-aus-hvn"
#HCP_CLIENT_ID = "bfc8BXF4b2Mgi8D7dU5QYfoH8xZBjMqG"
#HCP_CLIENT_SECRET = "OKbT2R6WZeY_78PPtSVO3knjEYrvVFGS1ETJAKIyVgDmqmD6zUHfeGZz-Jxvr4D7"
